# -*- coding: utf-8 -*-
"""finance_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gx04H2Ul_NKc4ViIWtGgL2bAnVbdJ1uy
"""

import pandas as pd
import random
from datetime import datetime, timedelta
import uuid

# Define our realistic merchant pool
merchants = [
    "UBER *TRIP", "AMZN Mktp US", "STARBUCKS STORE 1029",
    "NETFLIX.COM", "WHOLEFDS SQA", "SHELL OIL",
    "PAYROLL DIRECT DEP", "VENMO *PAYMENT", "TARGET T-092"
]

# Generate 100 random transactions over the last 90 days
data = []
start_date = datetime.now() - timedelta(days=90)

for _ in range(100):
    merchant = random.choice(merchants)

    # Payroll is a credit, everything else is a debit
    if merchant == "PAYROLL DIRECT DEP":
        amount = round(random.uniform(2000.00, 3500.00), 2)
        txn_type = "Credit"
    else:
        amount = round(random.uniform(5.00, 150.00), 2)
        txn_type = "Debit"

    random_days = random.randint(0, 90)
    txn_date = start_date + timedelta(days=random_days)

    data.append({
        "Transaction_ID": str(uuid.uuid4())[:8],
        "Date": txn_date.strftime("%Y-%m-%d"),
        "Merchant_Description": merchant,
        "Amount": amount,
        "Type": txn_type
    })

# Build the DataFrame and export to CSV
df = pd.DataFrame(data)
df.to_csv("synthetic_bank_export.csv", index=False)
print("Bank export generated successfully!")

import pandas as pd
import re

# Load the synthetic data we just created
df = pd.read_csv("synthetic_bank_export.csv")

# Define our categorization dictionary using regex patterns
category_mapping = {
    r'(?i).*UBER.*': 'Transportation',
    r'(?i).*SHELL.*': 'Transportation',
    r'(?i).*STARBUCKS.*': 'Dining',
    r'(?i).*NETFLIX.*': 'Entertainment',
    r'(?i).*WHOLEFDS.*': 'Groceries',
    r'(?i).*AMZN.*|.*TARGET.*': 'Shopping',
    r'(?i).*PAYROLL.*': 'Income',
    r'(?i).*VENMO.*': 'Peer-to-Peer'
}

def categorize_transaction(merchant):
    for pattern, category in category_mapping.items():
        if re.search(pattern, str(merchant)):
            return category
    return 'Uncategorized'

# Apply the function to create a new Category column
df['Category'] = df['Merchant_Description'].apply(categorize_transaction)

# Display the cleaned and categorized dataframe
print(df[['Date', 'Merchant_Description', 'Category', 'Amount']].head(10))

import sqlite3

# Connect to a local SQLite database (creates the file if it doesn't exist)
conn = sqlite3.connect('finance_engine.db')
cursor = conn.cursor()

# Create the Categories lookup table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Categories (
    Category_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Category_Name TEXT UNIQUE
)
''')

# Create the main Transactions fact table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Transactions (
    Transaction_ID TEXT PRIMARY KEY,
    Date DATE,
    Merchant TEXT,
    Amount REAL,
    Type TEXT,
    Category_ID INTEGER,
    FOREIGN KEY (Category_ID) REFERENCES Categories (Category_ID)
)
''')

conn.commit()
print("Relational database schema deployed successfully!")

# 1. Populate the Categories table (INSERT OR IGNORE prevents duplicates)
unique_categories = df['Category'].unique()
for cat in unique_categories:
    cursor.execute('INSERT OR IGNORE INTO Categories (Category_Name) VALUES (?)', (cat,))

# 2. Iterate through the dataframe and load the Transactions
for index, row in df.iterrows():
    # Retrieve the Foreign Key for the category
    cursor.execute('SELECT Category_ID FROM Categories WHERE Category_Name = ?', (row['Category'],))
    cat_id = cursor.fetchone()[0]

    # Insert the transaction using the retrieved Category_ID
    cursor.execute('''
    INSERT OR IGNORE INTO Transactions
    (Transaction_ID, Date, Merchant, Amount, Type, Category_ID)
    VALUES (?, ?, ?, ?, ?, ?)
    ''', (row['Transaction_ID'], row['Date'], row['Merchant_Description'], row['Amount'], row['Type'], cat_id))

conn.commit()

# 3. Prove it worked by querying the SQL database back into Pandas!
sql_query = '''
SELECT t.Date, t.Merchant, c.Category_Name, t.Amount
FROM Transactions t
JOIN Categories c ON t.Category_ID = c.Category_ID
LIMIT 5;
'''
test_output = pd.read_sql_query(sql_query, conn)
print(test_output)

analytics_query = '''
WITH DailySpend AS (
    SELECT
        Date,
        SUM(Amount) as Daily_Total
    FROM Transactions
    WHERE Type = 'Debit'
    GROUP BY Date
)
SELECT
    Date,
    Daily_Total,
    SUM(Daily_Total) OVER (
        ORDER BY Date
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS Rolling_30_Day_Burn
FROM DailySpend
ORDER BY Date DESC
LIMIT 10;
'''

burn_rate_df = pd.read_sql_query(analytics_query, conn)
print(burn_rate_df)

!pip install pdfplumber pandas

import pdfplumber
import pandas as pd

all_rows = []

with pdfplumber.open("statement.pdf") as pdf:
    for page in pdf.pages:
        table = page.extract_table()
        if table:
            for row in table:
                # Remove None values and strip whitespace from cells
                cleaned_row = [str(cell).strip() if cell is not None else "" for cell in row]
                # Filter out completely blank rows
                if any(cleaned_row):
                    all_rows.append(cleaned_row)

# Load into DataFrame without forcing strict column headers upfront
df_pdf = pd.DataFrame(all_rows)

# Inspect the raw structure
print(f"Extraction successful! Extracted {len(df_pdf)} rows.")
print(df_pdf.head(10))

# Inspect non-empty sample values for each extracted column
for col in df_pdf.columns:
    sample_vals = df_pdf[col].replace('', None).dropna().unique()[:3]
    print(f"Column [{col}]: Sample values -> {list(sample_vals)}")

import pandas as pd
import numpy as np
import re

# 1. Isolate the target columns based on your indices
df_clean = df_pdf[[0, 2, 3, 4]].copy()
df_clean.columns = ['Raw_Date', 'Merchant_Description', 'Debit', 'Credit']

# 2. Function to safely strip Naira symbols, commas, and convert to floats
def clean_currency(val):
    if not val or pd.isna(val) or str(val).strip() == '':
        return 0.0
    # re.sub removes anything that is NOT a digit or a decimal point
    cleaned = re.sub(r'[^\d.]', '', str(val))
    return float(cleaned) if cleaned else 0.0

df_clean['Debit'] = df_clean['Debit'].apply(clean_currency)
df_clean['Credit'] = df_clean['Credit'].apply(clean_currency)

# 3. Consolidate into 'Amount' and 'Type' to match our SQL schema
df_clean['Amount'] = np.where(df_clean['Debit'] > 0, df_clean['Debit'], df_clean['Credit'])
df_clean['Type'] = np.where(df_clean['Debit'] > 0, 'Debit', 'Credit')

# 4. Standardize dates and drop junk rows
# errors='coerce' forces PDF header text that isn't a date into a Null value
df_clean['Date'] = pd.to_datetime(df_clean['Raw_Date'], errors='coerce').dt.strftime('%Y-%m-%d')
df_clean = df_clean.dropna(subset=['Date'])

# 5. Finalize the dataframe structure
df_final = df_clean[['Date', 'Merchant_Description', 'Amount', 'Type']]

print("PDF Data Standardized!")
print(df_final.head())

# 4. Standardize dates using an explicit format and drop junk rows
df_clean['Date'] = pd.to_datetime(df_clean['Raw_Date'], format='%d %b %Y', errors='coerce').dt.strftime('%Y-%m-%d')
df_clean = df_clean.dropna(subset=['Date'])